### PR TITLE
Prepl reusing

### PR DESCRIPTION
**Pull request by raymcdermott**
some more testing to be done with the UI but nearly there for the code reorg

### CODE REVIEW

**Comment by mfikes** [comment]
I tried using this PR's code from Replete iOS and hit this:

```
Syntax error (ExceptionInfo) compiling at (script/build.clj:15:1).
Unable to resolve var: ns-resolve in this context at line 350 /Users/mfikes/.gitlibs/libs/github-replete-repl/replete-shared/4c2f64c1a9444b1fc2b8e83da4a81dec4310c079/src/replete/core.cljs
```

**Comment by mfikes** [comment]
With respect to the previous comment, here is the failing bit of code:

```
(defn ns-resolve
  "Returns the var to which a symbol will be resolved in the namespace, else
  nil."
  [ns sym]
  (#'repl/ns-resolve ns sym))
```

It looks like the qualified Var being used to access the private fn just needs to be updated to `#'replete.priv-repl/ns-resolve`

**Comment by raymcdermott** [comment]
@mfikes @wildthink and @roman01la  please check that this still works with your platform and I'll merge

**Comment by mfikes** [comment]
Replete iOS seems to be fine with `2d763ef05f9ffe37cd403caacbecf083b4bffb4f`

**Pull request merged**
