### PR TITLE
STASH: results being presented in prepl maps

### PR DESCRIPTION
**Pull request by raymcdermott**

### CODE REVIEW

**Comment by raymcdermott** [comment]
Please don't merge yet

**Comment by mfikes** [comment]
@raymcdermott Even though no review yet, one comment: Looks like your IDE is reformatting all the whitespace in the files.

**Comment by raymcdermott** [comment]
Yeah, that's odd. I don't get a clean diff on the file if I use the Cursive defaults or if I play with the most obvious high level options. What settings do you have?

**Comment by mfikes** [comment]
@raymcdermott Hrm. I suspect that this file represents different formats over the years, mostly adjusted over time to try to match that used in the ClojureScript tree.

**Comment by raymcdermott** [comment]
I'm gonna call this formatting done 😂

IO next

**Review by wildthink — APPROVED** [review]

**Comment by wildthink** [comment]
All good.

**Comment by raymcdermott** [comment]
Moved the PREPL code out to its own namespace to limit the blast radius of any breaking changes.

Unfortunately there is now a lot of duplication of private fns / data.

I'm wondering if we could have another `ns` that is shared between `repl` and `prepl` which specifically says it's not a public API but has a more relaxed set of compiler privacy permissions.

Other ideas welcome ;-)

**Comment by mfikes** [comment]
@raymcdermott I haven't looked at this in detail yet, but it looks like you have Cursive set to reformat the entire file upon save or some such.

**Review by mfikes — APPROVED** [review]

**Comment by raymcdermott** [comment]
superseded by a later PR

**Pull request closed without merging**
