### PR TITLE
Accommodate improved exception handling and printing in 1.10.516

### LINKED ISSUE #9: Accommodate improved exception handling and printing in 1.10.516
See https://github.com/planck-repl/planck/commit/bd4165e4448a2505aa6aacfb351373b074a4c6f3

### PR DESCRIPTION
**Pull request by mfikes**
Fixes #9

### CODE REVIEW

**Comment by mfikes** [comment]
This is a fairly straightforward copy of relevant code from Planck, plus the removal of some fns that were made dead code.

Test cases to try are at https://gist.github.com/mfikes/cca647f962f38edb599596f8e7bffc43
Will follow up with Replete Android and Replete iOS updates to depend on this SHA.

**Comment by roman01la** [comment]
It works. Though I can see differences with https://gist.github.com/mfikes/cca647f962f38edb599596f8e7bffc43 when running https://github.com/replete-repl/replete-android/pull/28

Here `08` produces `Execution error`, but according to the gist it should be `Syntax error`. Is that expected?
screen shot 2019-02-04 at 1 24 14 pm

**Comment by mfikes** [comment]
Yeah, the issue with `08` is reproducible in Planck. I've logged a ticket in that project. https://github.com/planck-repl/planck/issues/857

The issue could very much be upstream in the compiler, or some artifact of the way the reader is employed at runtime.

**Comment by roman01la** [comment]
Ok, I think it's minor issue and we can merge it now

**Comment by mfikes** [comment]
The 08 issue seems to be a trivial fix (in PR https://github.com/replete-repl/replete-shared/pull/13)

**Pull request merged**
