### PR TITLE
cljs 1.10.516

### PR DESCRIPTION
**Pull request by roman01la**

### CODE REVIEW

**Comment by mfikes** [comment]
@roman01la My guess is that, if we do this, then we will also want to revise things to accommodate the new exception stuff. (See https://github.com/planck-repl/planck/commit/bd4165e4448a2505aa6aacfb351373b074a4c6f3)
I don't mind putting together a PR for that stuff as well for inclusion in our beta.

**Review by mfikes — APPROVED** [review]

**Comment by mfikes** [comment]
Added #9

**Comment by roman01la** [comment]
That would be great!

**Comment by mfikes** [comment]
OK, I'll merge this now, and follow up with the changes needed for #9.

**Pull request merged**
